In [42]:
from Utils.YahooDataCollector import YahooDataCollector

stock = YahooDataCollector("tatamotors.NS")

[*********************100%%**********************]  1 of 1 completed

In [43]:
df = stock.hist
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
1991-01-02,20.959597,21.857864,20.959597,21.857864,15.738639,0
1991-01-03,20.959597,21.857864,20.959597,21.857864,15.738639,0
1991-01-04,21.857864,21.857864,21.857864,21.857864,15.738639,0
1991-01-07,20.360750,21.259020,20.061329,21.109308,15.199646,0
1991-01-08,21.109308,21.109308,21.109308,21.109308,15.199646,0
...,...,...,...,...,...,...
2024-04-18,996.349976,1003.099976,966.250000,971.349976,971.349976,13540490
2024-04-19,964.000000,967.950012,944.000000,963.200012,963.200012,15381310
2024-04-22,978.750000,978.750000,966.000000,973.549988,973.549988,7187959
2024-04-23,976.000000,994.500000,974.049988,986.750000,986.750000,7994116
2024-04-24,992.400024,995.900024,990.299988,992.650024,992.650024,1309080

In [44]:
stock.ticker.news

[{'uuid': '54bad350-d6a7-3da6-9284-3500cbcb0997',
  'title': 'Q1 2024 Invesco Ltd Earnings Call',
  'publisher': 'Thomson Reuters StreetEvents',
  'link': 'https://finance.yahoo.com/news/q1-2024-invesco-ltd-earnings-042110122.html',
  'providerPublishTime': 1713932470,
  'type': 'STORY',
  'relatedTickers': ['IVZ']},
 {'uuid': 'f87f310b-c207-305d-bffa-abe835c48679',
  'title': 'Q1 2024 United Parcel Service Inc Earnings Call',
  'publisher': 'Thomson Reuters StreetEvents',
  'link': 'https://finance.yahoo.com/news/q1-2024-united-parcel-inc-042039226.html',
  'providerPublishTime': 1713932439,
  'type': 'STORY',
  'relatedTickers': ['UPS']},
 {'uuid': '80f2569c-5e46-3ccf-a017-982bb0ea6aa1',
  'title': 'Tianqi Lithium Shares Dive After Warning of Wider Losses',
  'publisher': 'The Wall Street Journal',
  'link': 'https://finance.yahoo.com/m/80f2569c-5e46-3ccf-a017-982bb0ea6aa1/tianqi-lithium-shares-dive.html',
  'providerPublishTime': 1713932280,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/aitP30bRN9OdODnezgdGVg--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/14de42c9784c32e397d644df6b885852',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/Wiv8ngxXJdHiW72loBcvYA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/14de42c9784c32e397d644df6b885852',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]},
  'relatedTickers': ['002466.SZ']},
 {'uuid': '6e783597-4680-3ae7-8100-3cf06d1919f9',
  'title': 'Investing in Phoenix Mecano (VTX:PMN) a year ago would have delivered you a 16% gain',
  'publisher': 'Simply Wall St.',
  'link': 'https://finance.yahoo.com/news/investing-phoenix-mecano-vtx-pmn-041619396.html',
  'providerPublishTime': 1713932179,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/OB1nfJ1XGlebSq696rWQeQ--~B/aD00MzI7dz0xMTk0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/16016486ecb815bcffeea7a1908fff4e',
     'width': 1194,
     'height': 432,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/bB5.p_7KUNS98U5vL_8T1g--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/16016486ecb815bcffeea7a1908fff4e',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': 'dbd3ec15-04f4-3b84-9c87-3c0bd45c1590',
  'title': 'While institutions own 29% of Peach Property Group AG (VTX:PEAN), private companies are its largest shareholders with 44% ownership',
  'publisher': 'Simply Wall St.',
  'link': 'https://finance.yahoo.com/news/while-institutions-own-29-peach-041104600.html',
  'providerPublishTime': 1713931864,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/n0pgJtwwN7F.1RoyV3KnKA--~B/aD00MzI7dz0xMTk0O2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/53518648b6315faea839e9bb897d943a',
     'width': 1194,
     'height': 432,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/LonaSsZPu9AL1OHKL.PU6Q--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/simply_wall_st__316/53518648b6315faea839e9bb897d943a',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': '07837c2d-c8fc-346c-86c5-f1f4df9da8d3',
  'title': 'Stock market today: US stocks climb ahead of Tesla and mega-cap tech earnings',
  'publisher': 'Business Insider',
  'link': 'https://finance.yahoo.com/m/07837c2d-c8fc-346c-86c5-f1f4df9da8d3/stock-market-today%3A-us-stocks.html',
  'providerPublishTime': 1713931820,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/9PzqBkAUy4EC1zi8bPbEYA--~B/aD0yODY5O3c9MzgyNjthcHBpZD15dGFjaHlvbg--/https://media.zenfs.com/en/business_insider_articles_888/2dc221930119def48ca77116b2b42fa7',
     'width': 3826,
     'height': 2869,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/EkV8uRhtx5M9WWrNkj20NQ--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/business_insider_articles_888/2dc221930119def48ca77116b2b42fa7',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}},
 {'uuid': '02af2747-2f5f-3d54-83bd-a957bc8a75ad',
  'title': 'Q1 2024 AGNC Investment Corp Earnings Call',
  'publisher': 'Thomson Reuters StreetEvents',
  'link': 'https://finance.yahoo.com/news/q1-2024-agnc-investment-corp-040848210.html',
  'providerPublishTime': 1713931728,
  'type': 'STORY',
  'relatedTickers': ['AGNC']},
 {'uuid': 'afaeae57-4bc8-3804-9c65-4424834f4d2f',
  'title': 'Senate Passes Ukraine, Israel Aid Package After Monthslong Fight',
  'publisher': 'The Wall Street Journal',
  'link': 'https://finance.yahoo.com/m/afaeae57-4bc8-3804-9c65-4424834f4d2f/senate-passes-ukraine%2C-israel.html',
  'providerPublishTime': 1713931620,
  'type': 'STORY',
  'thumbnail': {'resolutions': [{'url': 'https://s.yimg.com/uu/api/res/1.2/7dND7aemVLq3vxKBHhCJjg--~B/aD02NDA7dz0xMjgwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/537cd2c50433ac32aa03c457f3720284',
     'width': 1280,
     'height': 640,
     'tag': 'original'},
    {'url': 'https://s.yimg.com/uu/api/res/1.2/EGV8LAtgLHwgMCW4WIG0NA--~B/Zmk9ZmlsbDtoPTE0MDtweW9mZj0wO3c9MTQwO2FwcGlkPXl0YWNoeW9u/https://media.zenfs.com/en/wsj.com/537cd2c50433ac32aa03c457f3720284',
     'width': 140,
     'height': 140,
     'tag': '140x140'}]}}]

In [46]:
import yfinance as yf

# Retrieve list of exchanges
exchanges = yf.Ticker('^BSESN').info['exchange']

# Filter for Indian exchanges
indian_exchanges = [exchange for exchange in exchanges if 'India' in exchange]

# Retrieve list of symbols for each exchange
indian_symbols = []
for exchange in indian_exchanges:
    ticker_list = yf.Tickers().tickers_on_exchange(exchange)
    indian_symbols.extend([ticker.info['symbol'] for ticker in ticker_list])

# Retrieve stock names
stock_names = {symbol: yf.Ticker(symbol).info['longName'] for symbol in indian_symbols}

# Print the results
print("Indian Stock Exchanges:", indian_exchanges)
print("Stock Symbols:", indian_symbols)
print("Stock Names:", stock_names)

Indian Stock Exchanges: []
Stock Symbols: []
Stock Names: {}

In [47]:
exchanges

'BSE'